### ISSUE TITLE
bower package jwt-client is not registered in the bower rigistry

### ISSUE THREAD

**Issue by remisb** [pauldijou/jwt-client#1]
when I'm installing jwt-client as a bower package it fails. Message I'm getting back is bower-bootstrap-accordion is not registered in the Bower registry and therefore the Bower client cannot find it by name.

Message I'm getting back is 

```
$ bower install jwt-client 
bower                        ENOTFOUND Package jwt-client not found
```

I guess you have to update readme file or finish with bower package registration.

**Comment by pauldijou** [comment]
My bad, I forgot to finish the registration process. I just did it now, it should be all good. And sorry for the delay, I wasn't really coding anymore for the last few months.
