### ISSUE TITLE
Does not work correctly with Browserify

### ISSUE THREAD

**Issue by nickw444** [pauldijou/jwt-client#3]
Might be user error, however I can't seem to get this to work correctly when bundling with Browserify. I have narrowed it down to being an issue with the `global` variable pattern you seem to be using in this package.

In the mean time, i'm using a personal fork here: https://github.com/nickw444/jwt-client/ which simply does a hacky patch to get this to work in Browserify.

**Comment by pauldijou** [comment]
Should be fixed in 0.2.0.

**Comment by nickw444** [comment]
Awesome. Thanks so much!
