### ISSUE TITLE
"Invalid calling object" error in isString function in IE

### ISSUE THREAD

**Issue by fmcgough** [pauldijou/jwt-client#4]
I've run into a bug using this library in Internet Explorer (version 11) - inside the isString helper function, the call to `toString.call(value)` results in a TypeError with message "Invalid calling object". A little experimentation suggests that replacing it with `Object.prototype.toString.call(value)` should fix the issue.

**Comment by pauldijou** [comment]
Thanks for the report! Should be fixed in 0.2.1. Mind giving it a try? I don't really have any Internet Explorer with me right now...

**Comment by fmcgough** [comment]
That's working perfectly for me now, thanks for the quick response!
